### PR TITLE
Fix on the PQ.

### PR DESCRIPTION
**Pull request by guidotag**
Important: Please cherry pick Feb09's commits. Feb06 was already pushed to apache/master.

The minor change is just something I saw while trying to fix another bug. A String's length might not be the same as the represented utf16's length.

The second change is on the PQ. Heapify was swapping incorrectly. This solved TestFuzzyQuery/TestFuzziness and TestFuzzyQuery/TestTieBreaker.

### CODE REVIEW

**Comment by guidotag** [comment]
What do you think @synhershko ?

**Comment by synhershko** [comment]
@guidotag this is mainly why I haven't pulled this in yet. I wasn't the one to bring this PQ implementation in so I wanted to review this carefully and haven't got the time to do that just yet.

Take a look here: https://github.com/apache/lucenenet/commit/0471466e0719b8f828e89fc7edaa481ad75ac2d8#diff-86df47eb5fd9dabe41b7624bcb97587aR362

This is another usage of the same PQ - it basically relies on `T` implementing `IComparable` - so while what you are suggesting is true, it is probably way more trickier than you think.

The right plan of attack here is to switch to using `IComparer<T>` (passed via a mandatory ctor param)

As a side-note, I'd very much like to verify this PQ implementation. I don't believe we have tests for it, and since its going to be quite central I want to validate its correctness, performance and thread-safety guarantees. Worth looking up in the history who brought it in and take it from there /cc @paulirwin

**Comment by guidotag** [comment]
Why changing to an IComparer<T>? It is much more natural to think PriorityQueue<T> as a PQ containing elements of type T, rather that letting T be a comparator class.

Regarding the PQ's tests, I'll start working on that. Since it seems to be a critical piece of code, I'll send an email just to tell I'll be on it.

**Comment by synhershko** [comment]
Because as you indicate, items are not compared based on one strategy always. See the link I posted for another example of this.

`IComparer` is more suitable for those scenarios. I'm not saying make `T` an `IComparer`, I'm saying lets remove the requirement for `T` to implement `IComparable` and instead provide PQ with an `IComparer`

**Comment by guidotag** [comment]
Oh, I got it! Yep, that seems a much more flexible approach. Unless you want to do it, I'll take care of that too.

**Comment by synhershko** [comment]
Go ahead!

**Comment by guidotag** [comment]
I realized that there are two different implementations of a PQ, one in Util and this one in Support. Do we have two different ones for some reason? A couple of things I've noticed:

- The Java version uses the Util's PQ. Moreover there seems to be no Support package, which seems to contain emulations of Java features not present in C#. 
- The Support's one is only used in the Search/TopTermsRewrite class. The Util's one is much more referenced.
- The only PQ's methods invoked from TopTermsRewrite are: PriorityQueue(int capacity), PriorityQueue(), T Peek(), T Poll() (dequeueing without failure if the PQ is empty), bool Offer(T item) (insertion) and int Count. All of these methods are provided by Util's PQ, with the exception of Poll which could be added with little effort.

All this facts make me think that we should replace the Support's duplicate by the Util's preexisting PQ.

**Comment by guidotag** [comment]
One more thing: The Util's one has some unit tests while the other one, as you remarked previously, does not.

**Comment by synhershko** [comment]
The Util one is taken directly from Java Lucene:

https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/util/PriorityQueue.java

This is also why it has unit tests.

Can you please verify the port of this class, and the tests, and move to using that one?

Worth noting the TTR usage is basically wrong - it should have used the one in Util: 
https://github.com/apache/lucene-solr/blob/lucene_solr_4_8_0/lucene/core/src/java/org/apache/lucene/search/TopTermsRewrite.java#L23

So let's verify the port of that PQ and move to using it, deprecating the one in Support. Once we stabilized everything I'll dig to see why it was introduced in the first place, and remove it after all required lessons were learned.

Good catch

**Comment by guidotag** [comment]
That's a good plan! I'll start working on this.

**Comment by guidotag** [comment]
@synhershko I finished reviewing Util's PQ and creating some more unit tests.
I could change this PQ to require a comparer in the constructors, rather than needing to inherit and overwrite the LessThan method, but, as you imagine, this would require changes all over the code.

This way of defining comparers via inheriting is flexible enough to allow two different comparers for the same data type, though you'll need to create two different PQ type's which is much less natural than just creating two different comparer functions and using them with the same generic PQ.

Passing a comparer seems a much better (and natural) approach to me, but since this would require a lot of changes I'd like to discuss it before doing any move.

**Comment by eladmarg** [comment]
@guidotag I Agree with you, passing comparer seems more naturally, more generic and more readable code.
We're at .net, so we should follow the attitude.

how many files involved with this change?

**Comment by guidotag** [comment]
It has 60 references from 20 different files.

**Comment by eladmarg** [comment]
maybe it is possible to assign default comparer <T> as default value

**Comment by synhershko** [comment]
@guidotag I think this can be closed now that #97 is merged? can the PQ from `Support` be removed now?

**Comment by guidotag** [comment]
Not yet. It remains changing all the references to Support's PQ. I'll take care of this right now, and after PRing that I'll close this one.

**Pull request closed without merging**
