### PR TITLE
Add Contributor's guide

### PR DESCRIPTION
**Pull request by SeanKilleen**
@synhershko wrote [A contributor's guide](http://markmail.org/message/czvc7z7jopxckbui) on the mailing list. 

Seems like the kind of thing that would make sense to put in the repository. :)

*The purpose of this PR is to:*

* Add the contributor's guide e-mail from Itamar to the repository
* Add both of the existing markdown documents as solution items to the Visual Studio solution.

### CODE REVIEW

**Comment by geobmx540** [comment]
Absolutely welcome - 


You should sign up for the wiki and makes adjustments to the getting started section - probably would be useful to break it into a few sections based on all Itamar wrote


~P



From: Sean Killeen
Sent: ‎Monday‎, ‎January‎ ‎19‎, ‎2015 ‎5‎:‎55‎ ‎PM
To: apache/lucenenet





@synhershko wrote A contributor's guide on the mailing list. 

Seems like the kind of thing that would make sense to put in the repository. :)

This is a work in progress so that others can comment on whether it's welcome. 

This will be my first contribution to the project; just wanted to add a little something to be helpful.



You can view, comment on, or merge this pull request online at:

  https://github.com/apache/lucenenet/pull/52

Commit Summary
Add Itamar's Contribution guide As-Is
Add Markdown folder to VS project
Change title to reflect Itamar's e-mail

File Changes
A CONTRIBUTING.md (121) 
M Lucene.Net.sln (8) 

Patch Links:
https://github.com/apache/lucenenet/pull/52.patch
https://github.com/apache/lucenenet/pull/52.diff

**Comment by SeanKilleen** [comment]
Glad it's welcome! Once I have it here I'm happy to port it to there. Have a few irons in the fire right now but I'm sure I can make it happen.

**Comment by SeanKilleen** [comment]
@geobmx540 cleaned up version is ready for review. **NOTE:** I'm working on my ICLA right now.

* Updated the PR to include what it's trying to achieve
* All of the initial formatting is done
* Content changes kept to a minimum (except language changes around moving to friendly links, etc.

**Comment by SeanKilleen** [comment]
FYI, my ICLA has now been submitted to Apache with a request to notify Lucene.net.

**Comment by geobmx540** [comment]
Both you and the committer group will get notice once the secretary has handled that - thanks!

I have a question that's probably general - more of style. Do we want to want to include a lot of the details here in the repo vs the wiki?

I lean towards making this much more of a summary and then pointing it to various parts of the wiki (getting started is now 4 different sub pages - in my attempt to break it up).

I'm open to what people thing?

**Comment by SeanKilleen** [comment]
It's a good question. Personally, when I approach a repo as a developer, I hope to see three things:

* A readme describing the project with some links, etc.
* A license file so I know what terms I'm working under
* Something that quickly tells me how to get started, and where my efforts would be well spent. 

A contributor's guide, IMO, makes the most sense closest to the contributions, and in this case, that's Github. That's why it felt natural to put it here rather than in the Wiki. 

Definitely a good idea to sort that preference out first, though.

**Comment by synhershko** [comment]
Thanks Sean

We may want to include some explanation on the folder structure, as well as probably removing the current status of things (which is bound to change)

**Comment by SeanKilleen** [comment]
@synhershko happy to remove the "current status" aspects if you want; let me know. I was thinking it makes sense to keep them there until such a time as they maybe were broken up into GitHub issues that could be tagged with `up-for-grabs`. 

A future PR could easily remove them from the guide. However, I think it still represents the best place and piece of information for someone to get started. I actually really liked that; without an issues list, it's nice to have something to point towards a "good place to start".

**Comment by synhershko** [comment]
I'm all in for the `up-for-grabs` thing, and would have done it already if we had github issues enabled..

**Comment by SeanKilleen** [comment]
FYI, Apache just notified me that my ICLA has been processed and we're all good there.

If someone enables the issues, I'd be happy to try to translate some of the items here and then remove them in a separate PR.

For now, I think it makes sense to leave it all here and push it as-is so at least a dev can get all the information in one spot.

**Comment by geobmx540** [comment]
Is there another project that has github issues enabled I can look at? Or I can email infra and see what they say

Date: Tue, 20 Jan 2015 06:44:26 -0800

**Comment by synhershko** [comment]
Email Infra, I think no Apache project has it enabled. There's JIRA for that :(

**Comment by michaelherndon** [comment]
Apache has this pattern of maintaining all data related to projects in house. 

Hence, mailing lists instead of google hangouts, hosted jira, etc. There are some tools that will push issues from Jira to Github issues and separate tools to push Github issues to Jira.  It may be worth using a win / win  request of enabling issues and pushing issues into Jira.

**Comment by SeanKilleen** [comment]
So given that those are separate issues, can we get this one merged in as is and go from there?

**Comment by synhershko** [comment]
Get you git squash please?

**Comment by SeanKilleen** [comment]
Ooops. New to squashing, and I think I may not have done the interactive rebase quite right. I'll see what I can do on it.

**Comment by synhershko** [comment]
@SeanKilleen no, basically you should see only one commit here https://github.com/SeanKilleen/lucenenet/compare/AddContributorsGuide

**Pull request closed without merging**
