### PR TITLE
Analysis work

### PR DESCRIPTION
**Pull request by synhershko**

### CODE REVIEW

**Comment by NightOwl888** [comment]
Is anyone working on Analysis now? I would like to take a stab at making the StandardAnalyzer and its ~20 dependencies  compile.

**Comment by synhershko** [comment]
Yes, this is my WIP branch. CharArrayMap and CharArraySet are a bit buggy still (tests are failing) and need to wipe those bugs out. I think this branch has all my changes (no local uncommitted changes), so go ahead. I believe all the files were ported and committed, just not included in the solution if they are not compiling or have some more work left in them.

**Comment by NightOwl888** [comment]
FYI - I am still working on this. I managed to get past the infinite recursion problem. I have completed nearly all of the standard and core namespaces and ported over 250 tests, with 225 of them passing. Most of the ones that are failing I believe are due to the CharArraySet returning incorrect numbers, which later on causes the Character.IsLetter method to crash.

You can view my WIP over here: https://github.com/NightOwl888/lucenenet/tree/analysis-work

**Comment by synhershko** [comment]
Closing in favor of #179

**Comment by synhershko** [comment]
Opening back as this is going to be the branch we work on to get this great work merged into master. cc @hristopherHaws @NightOwl888

**Comment by synhershko** [comment]
Still some work left, @NightOwl888 explains here: https://github.com/apache/lucenenet/pull/182#issuecomment-242906624

**Pull request merged**
