### PR TITLE
Simplifies solution with no-targets projects for build folders

### PR DESCRIPTION
**Pull request by Shazwazza**
Simplifies solution with no-targets projects for build folders:

Solution now looks like this:

image

and removes a lot of hard coded values in the sln file

### CODE REVIEW

**Comment by NightOwl888** [comment]
Yeah, I should have mentioned not to touch the `.build` folder because we use the same config in other projects, but I guess we can deal with it.

The `TestTargetFramework.props` file, is not visible now, though. I suppose we could move the file up to the `.build` folder so it will be visible again, but also need to update all of the references to that physical file to move it there.

**Comment by NightOwl888** [comment]
Or maybe just add it as a linked file. That should work.

**Comment by Shazwazza** [comment]
Yeah I just left the root files in the Solution Items folder manually. I can add that one in.

**Comment by Shazwazza** [comment]
I added that in now

**Review by NightOwl888 — APPROVED** [review]

**Pull request merged**
