### PR TITLE
LUCENET-555 Removing dependency on external zip library.

### PR DESCRIPTION
**Pull request by EMaher**
- Modifying CompressionMode to use System.IO.Compression.DeflateStream and remove dependency on external zip library.  Verfied AbstractCompressionMode tests passed.
- Modifying CompressionTools to use System.IO.Compression.DeflateStream and remove dependency on external zip library.
- Removing unused fuction in TestUtils that depended on external zip library.
- Adding ignore for project.lock.json files.

### CODE REVIEW

**Comment by synhershko** [comment]
Looks good, thanks!

**Comment by synhershko** [comment]
@EMaher hey, merging this broke compilation (should have tried it locally first!). Can you please have a look?

**Comment by Tasteful** [comment]
It's probably failing for the interpolated string (https://msdn.microsoft.com/en-us/library/dn961160.aspx) on https://github.com/apache/lucenenet/commit/e218ff63d0b22cbe39543986f0382f241cf47c24#diff-343b91381036b34a5e84eebc117858d8R241 

Visual Studio 2015 is using Roslyn for compilation (and usage of C#6). TC probably using the old compiler and cant use the C#6 features.

Enable the Roslyn compiler on the TC can probably be done with the Microsoft.CodeDom.Providers.DotNetCompilerPlatform/Microsoft.Net.Compilers nuget-package or the codebase should only use earlier C# specification.

**Comment by EMaher** [comment]
It is the string interpretation causing the build to fail.  My apologies.  https://github.com/apache/lucenenet/pull/164 removes the use of the C# 6 features.  I'll make sure to avoid until C# 6 features until the CI build is ready for them.

**Pull request merged**
